# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: candlestick_pattern.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'candlestick_pattern.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63\x61ndlestick_pattern.proto\x12\x10\x65ous.patterns.v1\"\x14\n\x12HealthCheckRequest\"2\n\x13HealthCheckResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07\x62\x61\x63kend\x18\x02 \x01(\t\"k\n\x13ScanPatternsRequest\x12\x11\n\ttimeframe\x18\x01 \x01(\t\x12\x10\n\x08patterns\x18\x02 \x03(\t\x12/\n\x07symbols\x18\x03 \x03(\x0b\x32\x1e.eous.patterns.v1.SymbolKlines\"G\n\x0cSymbolKlines\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\'\n\x06klines\x18\x02 \x03(\x0b\x32\x17.eous.patterns.v1.Kline\"b\n\x05Kline\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\r\n\x05\x63lose\x18\x05 \x01(\x01\x12\x0e\n\x06volume\x18\x06 \x01(\x01\"N\n\x14ScanPatternsResponse\x12\x36\n\x07results\x18\x01 \x03(\x0b\x32%.eous.patterns.v1.SymbolPatternResult\"\x7f\n\x13SymbolPatternResult\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\ttimeframe\x18\x02 \x01(\t\x12\x13\n\x0bsignal_time\x18\x03 \x01(\x03\x12\x30\n\x07signals\x18\x04 \x03(\x0b\x32\x1f.eous.patterns.v1.PatternSignal\"/\n\rPatternSignal\x12\x0f\n\x07pattern\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\x32\xd6\x01\n\x19\x43\x61ndlestickPatternService\x12]\n\x0cScanPatterns\x12%.eous.patterns.v1.ScanPatternsRequest\x1a&.eous.patterns.v1.ScanPatternsResponse\x12Z\n\x0bHealthCheck\x12$.eous.patterns.v1.HealthCheckRequest\x1a%.eous.patterns.v1.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'candlestick_pattern_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=47
  _globals['_HEALTHCHECKREQUEST']._serialized_end=67
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=69
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=119
  _globals['_SCANPATTERNSREQUEST']._serialized_start=121
  _globals['_SCANPATTERNSREQUEST']._serialized_end=228
  _globals['_SYMBOLKLINES']._serialized_start=230
  _globals['_SYMBOLKLINES']._serialized_end=301
  _globals['_KLINE']._serialized_start=303
  _globals['_KLINE']._serialized_end=401
  _globals['_SCANPATTERNSRESPONSE']._serialized_start=403
  _globals['_SCANPATTERNSRESPONSE']._serialized_end=481
  _globals['_SYMBOLPATTERNRESULT']._serialized_start=483
  _globals['_SYMBOLPATTERNRESULT']._serialized_end=610
  _globals['_PATTERNSIGNAL']._serialized_start=612
  _globals['_PATTERNSIGNAL']._serialized_end=659
  _globals['_CANDLESTICKPATTERNSERVICE']._serialized_start=662
  _globals['_CANDLESTICKPATTERNSERVICE']._serialized_end=876
# @@protoc_insertion_point(module_scope)
