# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import candlestick_pattern_pb2 as candlestick__pattern__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in candlestick_pattern_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CandlestickPatternServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScanPatterns = channel.unary_unary(
                '/eous.patterns.v1.CandlestickPatternService/ScanPatterns',
                request_serializer=candlestick__pattern__pb2.ScanPatternsRequest.SerializeToString,
                response_deserializer=candlestick__pattern__pb2.ScanPatternsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/eous.patterns.v1.CandlestickPatternService/HealthCheck',
                request_serializer=candlestick__pattern__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=candlestick__pattern__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class CandlestickPatternServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ScanPatterns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CandlestickPatternServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScanPatterns': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanPatterns,
                    request_deserializer=candlestick__pattern__pb2.ScanPatternsRequest.FromString,
                    response_serializer=candlestick__pattern__pb2.ScanPatternsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=candlestick__pattern__pb2.HealthCheckRequest.FromString,
                    response_serializer=candlestick__pattern__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eous.patterns.v1.CandlestickPatternService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eous.patterns.v1.CandlestickPatternService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CandlestickPatternService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScanPatterns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eous.patterns.v1.CandlestickPatternService/ScanPatterns',
            candlestick__pattern__pb2.ScanPatternsRequest.SerializeToString,
            candlestick__pattern__pb2.ScanPatternsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eous.patterns.v1.CandlestickPatternService/HealthCheck',
            candlestick__pattern__pb2.HealthCheckRequest.SerializeToString,
            candlestick__pattern__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
